# -*- coding: utf-8 -*-
"""IrisNB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cnZEEXOcqH5rfz30iqf_OUcTLZMQcywt
"""

import pandas as  pd
df=pd.read_csv('/content/Iris.csv')
df

df.head(5)

df.tail(5)

df.dtypes

df1=df.drop(['Id'],axis=1)
df1

df1.shape

x=df1.iloc[:,:-1].values
x

y=df1.iloc[:,-1].values
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

x_test

y_train

y_test

from sklearn.preprocessing import StandardScaler
stscl=StandardScaler()
stscl.fit(x_train)
x_train=stscl.transform(x_train)
x_test=stscl.transform(x_test)
x_train

from sklearn.naive_bayes import GaussianNB
data=GaussianNB()
data.fit(x_train,y_train)
y_pred=data.predict(x_test)
y_pred

y_test

from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
label=['Iris-versicolor','Iris-virginica','Iris-setosa']
mat=confusion_matrix(y_test,y_pred)
dis=ConfusionMatrixDisplay(mat,display_labels=label)
dis.plot()
mat

from sklearn.metrics import accuracy_score
acc=accuracy_score(y_test,y_pred)
acc